---
title: "Replication of Surveillance Cues Enhance Moral Condemnation by Bourrat, Baumard, & McKay (2011, Evolutionary Psychology)"
author: "Catie Connolly (catiec@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction 

### Experiment Summary

This experiment explores cooperation and the role of moral judgment in representing the self as a cooperative partner. To study this, Bourrat, Baumard, & McKay (2011) asked participants to read 2 vignettes that depicted individuals committing moral transgressions, and to rate these transgressions on a Likert scale where 1 was "morally unacceptable" and 7 was "morally acceptable." In the control condition, there was a picture of flowers between the vignette and the Likert scale; in the experimental condition, there was a picture of two eyes gazing at the participant. The eyes were meant to evoke the feeling of being watched (although the participants were always alone as they completed the study). 

The researchers found a significant difference between conditions such that individuals in the experimental condition rated the moral transgressions as less acceptable than individuals in the control condition. This finding suggests that even a very subtle cue of being watched can cause people to make harsher moral judgments. I aim to replicate these findings.

### Project Justification

I am currently inexperienced in R and hope to develop my skills further by building a project from scratch. By collecting my own data and cleaning/tidying that data, as well as by analyzing a 2x2 experimental paradigm, I will be developing skills that will be of great use to me throughout grad school. Furthermore, I am interested in cooperation between individuals and the ways in which we portray ourselves as "cooperative", and am interested in whether this finding will replicate, thus suggesting that strong demonstrated morals are somehow demanded by social circumstances. Furthermore, I hope to probe questions about how we define identity, and how identity can shift contextually according to the characteristics of a given situation. Thus, looking at a minimal paradigm like the one in this experiment, and the ways in which it may still impact moral judgments in meaningful ways, will be an exciting way to better understand how we conceptualize our identity in the real or imagined presence of others. 

### Required Stimuli and Expected Procedure 

This experiment will require no physical materials, given that the experiment will be entirely online via the MTurk online crowdsourcing platform (due to the in-person restrictions place on research by the COVID-19 pandemic, as well as time and resource constraints). While the original experiment took place in person, the participant was always alone during the study, thus justifying the use of MTurk since in-person experimenters were not necessary to carry out the study. 

The physical materials used during the original study will thus be converted to a digital form for administration on Qualtrics via MTurk. The survey will consist of 2 pages, each with one moral vignette, a picture of eyes or flowers (depending on random condition assignment), and a Likert scale from 1-7 for rating of moral acceptability. 

The original study was conducted with 91 volunteers from a Paris University, and participants were not compensated for their participation. Given MTurk participants are unlikely to complete an unpaid study, participants in the replication study will be paid a small fee for their time. 

### Anticipated Challenges

I anticipate that cleaning and tidying data from 91 participants will prove challenging, given that I have not worked with datasets in R in the past. In general, analyzing my own dataset for the first time combined with utilizing R to do so is a necessary challenge I will have to overcome to better develop both my R and data analysis chops.  

### Related Links 

The GitHub repository for this replication project can be found [here.](https://github.com/psych251/bourrat2011)

The original paper and subject of the replication project can be found [here.](https://github.com/psych251/bourrat2011/blob/master/original_paper/bourrat2011.pdf)

<!-- This is the end of the introduction section. -->

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

I anticipate collecting data from approximately 91 mTurkers to match the original sample size. I will limit the sample to American mTurkers who are fluent in English in order to ensure that participants are able to complete the survey to the best of their ability. 

### Materials

The original study used vignettes printed on A4 sheets of paper, with a picture of either eyes or flowers (depending on condition assignment) before a Likert scale. Given that the replication study will be conducted on Qualtrics via mTurk, the original stimuli will be presented in an online format, keeping all formatting equivalent to the greatest extent possible. 

### Procedure	

"Ninety-one participants were recruited in various libraries of the Campus Universitaire de Jussieu in Paris. Participation was voluntary and without remuneration. In an effort to minimize conscious concerns about the reputational consequences of their responses (which we felt might swamp the more subtle effects of our independent variable), we elected not to collect any personal (e.g., demographic) information from participants."

Given that this replication study will be conducted over mTurk, we will instead sample from the available worker population. Additioanlly, the original stimuli were presented in French--because the current researcher is not familiar with French, the replication study will instead use a US population and present all stimuli in English. This study will also pay mTurkers a small fee for their time rather than avoid remuneration altogether. Finally, like the original study, we will avoid collecting demographic information so as to avoid activating identity-relevant concepts that may interfere with participant responses to the moral vignettes by invoking a sense of moral duty. 

"Each participant was given two vignettes to read, printed on opposite sides of a single A4 sheet of paper. The vignettes were taken from Schnall, Haidt, Clore and Jordan (2008), and each described a moral violation: finding a wallet and keeping the money in one case, and falsifying a resume in the other (see the appendix for the original English versions, which were translated into French for the present study). Participants were instructed to rate the moral acceptability of each vignette on a nine-point Likert scale printed at the bottom of the page (1 = Morally unacceptable; 9 = Morally acceptable). Participants were directed to complete the task alone. The experimenter returned a few minutes later to collect the completed sheets."

As stated above, the printed stimuli will instead be presented in an online survey format on Qualtrics via mTurk. Otherwise, the stimuli will be identical to those used in the original study. 

"Participants were assigned randomly to one of two conditions. In the eyes condition (n = 43) a 47 x 17 mm image of a pair of eyes (see Figure 1a) was displayed on each side of the sheet between the vignette and the associated Likert scale. In the flowers condition (n = 48) the image was of white flowers (see Figure 1b)."

This aspect of the experiment will be carried out exactly as specified in the original paper. 

### Analysis Plan

"As the data were not normally distributed, we used a non-parametric test for our analyses. For the wallet vignette, the median rating of moral acceptability was 2 in the eyes condition and 3 in the flowers condition; the distributions in the two conditions were significantly different (Mann-Whitney U = 789, p = 0.024, one- tailed). For the resume vignette, the median rating was 3 in the eyes condition and 5 in the flowers condition; the distributions in the two conditions again differed significantly (Mann–Whitney U = 750, p = 0.016, one-tailed)."

The above excerpt from the original paper specifies the data analysis strategy utilized. Assuming this replication project also produces data that is not normally distributed, I will use the Mann-Whitney U Test (Wilcoxon Rank Sum) to analyse whether the distributions of moral evaluations in the two conditions are statistically significant. 

If, however, the data are normally distributed, I will instead use a t-test as the main analysis of interest. 

Currently, there are no expectations that data will need to be excluded. In order to assess the question of interest (whether the condition of eyes or flowers impacts moral evaluations), data will be organized by vignette to best assess the impact of each condition on moral evaluation of each respective vignette. 

### Differences from Original Study

The most important differences between the original study and replication study are 1) the demographic characteristics of the sample, namely location and language, and 2) method of survey presentation. 

Regarding 1), given the current researcher's knowledge base and lack of knowledge of French, this study will be conducted in English using a United States-based population. The original paper provided the English version of the vignettes, which will be used verbatim. Country of residence and ethnicity were not considered important factors in the original study, indicating that the orignally observed effect should generalize across populations. Similarly, it is important to note that the original study utilized convenience sampling amongst French university students, while the current study will more broadly sample from American mTurkers; again, this was not mentioned as specifically relevant in the original paper, and therefore we expect the original effects to persist in spite of this difference. 

Regarding 2), the organization of this course as well as the current constraints on in-person studies due to the COVID-19 pandemic limit this study to online presentation only. Rather than distributing paper surveys, we will link mTurkers to a Qualtrics survey using the same design characteristics as the original study. Because the original study involved specifically leaving participants alone to fill out the study, there should be no issues presented by the lack of an in-person experimenter for this study. Additionally, because all stimuli was static in the original study, there is no reason to believe online presentation should alter the results. 

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
I plan to organize the data by vignette in order to compare the effects of condition within each vignette. 

```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

I will analyze the data, organized into the two vignettes and the two conditions within each vignette, using the Mann-Whitney U test to compare the impact of condition on moral evaluation of each respective vignette. 

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
